image: node:alpine

stages:
  - install
  - lint-code
  - build
  - deploy


cache:
  key: vitepro
  paths:
    - node_modules
  

job_install:
  stage: install
  tags:
    - vite
  script:
    - npm i -f -g pnpm
    - pnpm install --no-frozen-lockfile

job_build:
  stage: build
  tags:
    - vite
  script:
    - pnpm build:h5

job_deploy:
  stage: deploy
  image: docker
  tags:
    - vite
  script:
    - docker build -t viteimages .
    - if [ $(docker ps -aq --filter name=myvite-container) ]; then docker rm -f myvite-container;fi
    - docker run -d -p 8082:80 --name myvite-container viteimages

