image: node:alpine

stages:
  - install
  - lint-code
  - build
  - deploy


cache:
  key: vitepro
  paths:
    - node_modules
  

job_install:
  stage: install
  tags:
    - vue3-cicd
  script:
    - npm install

job_build:
  stage: build
  tags:
    - vue3-cicd
  script:
    - npm run build

job_deploy:
  stage: deploy
  image: docker
  tags:
    - vue3-cicd
  script:
    - docker build -t viteimages .
    - if [ $(docker ps -aq --filter name=myvue3-container) ]; then docker rm -f myvite-container;fi
    - docker run -d -p 8083:80 --name myvue3-container viteimages

